#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Sys-SigAction
Version  : 0.23
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/L/LB/LBAXTER/Sys-SigAction-0.23.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/L/LB/LBAXTER/Sys-SigAction-0.23.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libsys-sigaction-perl/libsys-sigaction-perl_0.23-1.debian.tar.xz
Summary  : 'Perl extension for Consistent Signal Handling'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Sys-SigAction-man

%description
Sys/SigAction
Sys::SigAction provides EASY access to POSIX::sigaction() for signal
handling on systems the support sigaction().

%package man
Summary: man components for the perl-Sys-SigAction package.
Group: Default

%description man
man components for the perl-Sys-SigAction package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Sys-SigAction-0.23
mkdir -p %{_topdir}/BUILD/Sys-SigAction-0.23/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Sys-SigAction-0.23/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Sys/SigAction.pm
/usr/lib/perl5/site_perl/5.26.1/Sys/SigAction/Alarm.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Sys::SigAction.3
